spring:
  datasource:
    url: jdbc:mysql://localhost:3306/develhope
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  logging:
    level:
      org.springframework.cache: DEBUG
server:
  port: 9191
